export { Modal, default } from './Modal';
export {
  resolveModalConfig,
  getModalDataAttributes,
  getModalStyleVars,
  buildResponsiveStyleSheet,
  RADIUS_TOKENS,
  SHADOW_TOKENS,
  SIZE_WIDTH_TOKENS,
  SIZE_HEIGHT_TOKENS,
} from './resolveModalConfig';
export { defaultModalConfig, modalPresets } from './modal.config';
export type {
  ModalProps,
  ModalConfig,
  ModalConfigInput,
  ModalSize,
  ModalPosition,
  ModalAppearance,
  RadiusToken,
  ShadowToken,
  AnimationType,
  Breakpoint,
  Responsive,
  DeepPartial,
  BackgroundConfig,
  BorderConfig,
  BorderSideConfig,
  RadiusConfig,
  ShadowConfig,
  OverlayConfig,
  AnimationConfig,
  HeaderConfig,
  BodyConfig,
  FooterConfig,
  CloseButtonConfig,
  ThemeConfig,
  SizeConfig,
} from './Modal.types';
